### ISSUE TITLE
Flora.ds

### ISSUE THREAD

**Issue by franklinjavier** [brunabites/designsystemsbrasileiros#4]
Já enviamos pelo forms, mas gostaria de registrar por aqui também.
Flora.ds é o design system do [@grupoboticario](https://github.com/grupoboticario)

![image](https://user-images.githubusercontent.com/440220/157539939-b0f3635d-ae3b-4970-86e7-4d290ccca6e2.png)

**Comment by brunabites** [comment]
Publicado: https://designsystemsbrasileiros.com/florads

**Comment by franklinjavier** [comment]
Thanks
