### ISSUE TITLE
Link quebrado para o website

### ISSUE THREAD

**Issue by raphaelcunha** [brunabites/designsystemsbrasileiros#5]
The link in repo is broken!

Correct.
https://designsystemsbrasileiros.com

Incorrect.
https://designsystemsbrasileiros.com**.br**

![Screen Shot 2022-03-24 at 16 30 37](https://user-images.githubusercontent.com/3853552/159995684-7c3b53bd-d971-49bc-a7eb-31f4019abec0.png)

**Comment by brunabites** [comment]
Thanks, Raphael. Already fixed it.
